Gestion-de-Accidentes-SV/urls.py
from django.contrib import admin
from django.urls import path
from gestionAccidentes import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.inicio, name="inicio"),
    path('listaDeAccidentes/',views.listaDeAccidentes, name="listaDeAccidentes"),
    path('registrarAccidente/',views.registrarAccidente, name="registrarAccidente"),
    path('Detalles/<id>',views.Detalles,name="detalles"),
    path('reportar/<id>',views.reportar, name="reportar"),
    path('accounts/login/',views.IniciarSesion, name="IniciarSesion"),
    path('Registrarse/',views.Registrarse, name="Registrarse"),
    path('cerrarSesion/',views.cerrarSesion, name="cerrarSesion"),
   
]
urlpatterns +=static(settings.MEDIA_URL,document_root =settings.MEDIA_ROOT)

gestionAccidentes/models.py
from django.db import models
from django.contrib.auth.models import User

class ReporteAccidente(models.Model):
    descripcion=models.CharField(max_length=100)
    latitud=models.CharField(max_length=50)
    longitud=models.CharField(max_length=50)
    lugar=models.CharField(max_length=50)
    departamento=models.CharField(max_length=20) 
    municipio=models.CharField(max_length=30)    
    fecha=models.DateTimeField(auto_now_add=True)
    user=models.ForeignKey(User, on_delete=models.CASCADE,verbose_name="usuario")
    def __unicode__(self):
        return self.nombre

    def __str__(self):
        return str(self.id)
    

class DatosExtra(models.Model):
    cantVictimas=models.IntegerField(blank=True,null=True, verbose_name="Cantidad de victimas")
    foto=models.ImageField(upload_to ='images',blank=True,null=True)
    accidente=models.OneToOneField(ReporteAccidente, on_delete=models.CASCADE)
    
class Reporte(models.Model):
    accidente=models.ForeignKey(ReporteAccidente, on_delete=models.CASCADE)
    user=models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="usuario")


gestionAccidentes/forms.py
from django import forms
from .choices import Departamentos, Filtros
from .models import DatosExtra, ReporteAccidente
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

class AccidenteForm(forms.ModelForm):
    descripcion=forms.CharField(max_length=100, widget=forms.Textarea(attrs={'rows':'3'}))
    departamento=forms.ChoiceField(choices=Departamentos)
    class Meta:
        model=ReporteAccidente
        exclude=['user','municipio']

class DatosExtraForm(forms.ModelForm):
    cantVictimas=forms.IntegerField(min_value=0, label="Cantidad de victimas", required=False)
    class Meta:
        model=DatosExtra
        exclude=['accidente']
      
class FiltroForm(forms.Form):
    filtrar_por=forms.ChoiceField(choices=Filtros)
    buscar=forms.CharField()

class loginForm(AuthenticationForm):
    username=forms.IntegerField(label="DUI",min_value=0, max_value=999999999)
    class Meta:
        fields='__all__'
    
        
   

class RegistroForm(UserCreationForm):
    username=forms.IntegerField(label="DUI",min_value=0, max_value=999999999)
    class Meta:
        model=User
        fields=['username','password1','password2']
    

    def __init__(self, *args, **kwargs):
        super(RegistroForm, self).__init__(*args, **kwargs)
        self.fields['username'].help_text = ''



gestionAccidentes/views.py
from email import message
from django.shortcuts import get_object_or_404, render, redirect
from gestionAccidentes.models import DatosExtra, ReporteAccidente, Reporte
from .forms import AccidenteForm, DatosExtraForm, FiltroForm, loginForm, RegistroForm
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.contrib import messages

def IniciarSesion(request):
    if request.method=="POST":
        form=loginForm(request, data=request.POST)
        if form.is_valid():
            usuario=authenticate(username=form.cleaned_data['username'],password=form.cleaned_data['password'])
            if usuario:
                login(request, usuario) 
                return redirect('inicio')  
    else:
        form=loginForm()
    return render(request, "IniciarSesion.html",{"form":form})

def Registrarse(request):
    if request.method=="POST":
        form=RegistroForm(request.POST)
        if form.is_valid():
            usuario=form.save()
            login(request, usuario)
            return redirect('inicio')
    else:        
        form=RegistroForm()
    return render(request, "Registrarse.html",{"form":form})

@login_required
def inicio(request):

    return render(request,"inicio.html")

@login_required
def listaDeAccidentes(request):
    form=FiltroForm(request.POST)
    if request.method=="POST" and form.is_valid():
        if form.cleaned_data['filtrar_por']=="Departamento":
            accidentes=ReporteAccidente.objects.filter(departamento__iexact=form.cleaned_data['buscar']).order_by('-fecha')          
            form=FiltroForm()
        else:
            accidentes=ReporteAccidente.objects.filter(municipio__iexact=form.cleaned_data['buscar']).order_by('-fecha')          
            form=FiltroForm()
    else:
        accidentes=ReporteAccidente.objects.all().order_by('-fecha')
        form=FiltroForm()
    return render(request,"listaDeAccidentes.html",{"accidentes":accidentes,  "filtro":form})

@login_required
def registrarAccidente(request):
    if request.method=="POST":
        accidente=ReporteAccidente()
        form=AccidenteForm(request.POST)
        datosExtra=DatosExtra()
        form2=DatosExtraForm(request.POST, request.FILES)
        if form.is_valid():
            accidente=form.save(commit=False)
            accidente.municipio=request.POST.get('municipio')
            accidente.user=request.user
            accidente.save()
            datosExtra=form2.save(commit=False)
            datosExtra.accidente=accidente
            datosExtra.save()
            return redirect('listaDeAccidentes')
    else:
        form=AccidenteForm()
        form2=DatosExtraForm()
    return render(request,"registrarAccidente.html", {'form':form,'form2':form2})

@login_required
def Detalles(request, id):
    accidente=get_object_or_404(ReporteAccidente, id=id)
    
    form=AccidenteForm(instance=accidente)
    detalles=DatosExtra.objects.filter(accidente=accidente).first()
    if detalles:
        form2=DatosExtraForm(instance=detalles)
    else:
        form2=DatosExtraForm()
    return render(request, "detalles.html",{"form":form, "form2":form2, "detalles":detalles,"accidente":accidente})

@login_required
def reportar(request, id):
    accidente=get_object_or_404(ReporteAccidente, id=id)
    reporteExiste=Reporte.objects.filter(accidente=accidente, user=request.user)
    if(reporteExiste):
        return redirect('listaDeAccidentes')
    else:
        reporte=Reporte()
        reporte.accidente=accidente
        reporte.user=request.user
        reporte.save()
        return  redirect('listaDeAccidentes')

@login_required
def cerrarSesion(request):
    logout(request)
    return redirect('inicio')

gestionAccidentes/templates/IniciarSesion.html
{% load crispy_forms_tags %}
<html>

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="/static/css/style.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/login.css">
</head>

<body>
    <div class="d-flex align-items-center justify-content-center ">
        <div class="row content d-flex justify-content-center align-items-center col-5" style="height:100vh">
            <div class="">
                <div class="box shadow bg-white p-4 align-content-center col-12">
                    <h1 class="p-1 text-center">Inicio de sesión</h1>
                    <form action="" class="form-control col-10 text-center" method="POST">
                        {% csrf_token %}
                        <table class="table col-10">{{form.as_table}}</table>
                        <div class="d-grid gap-2 col-12 mx-auto mt-3">
                            <input type="submit" class="btn-primary btn-lg" value="Iniciar sesión">
                        </div>

                        <p class="mt-4">¿No estas registrado? <a href="{% url 'Registrarse' %}">Registrate</a></p>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

gestionAccidentes/templates/Registrarse.html
{% load crispy_forms_tags %}
<html>

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="/static/css/style.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/login.css">
</head>

<body>
    <div class="d-flex align-items-center justify-content-center ">
        <div class="row content d-flex justify-content-center align-items-center col-4" style="height:100vh">
            <div class="">
                <div class="box shadow bg-white p-4 align-content-center col-12">
                    <h1 class="text-center">Usuario Nuevo</h1>
                    <form method="POST" class="form-control form-check-inline">
                        {% csrf_token %}
                        <div class="input-group">
                            {{form.username|as_crispy_field}}</div>

                        <div class="input-group">{{form.password1|as_crispy_field}}</div>
                        <div class="input-group">{{form.password2|as_crispy_field}}</div>
                        <input type="submit" class="btn btn-success" value="Registrarse">
                        <p>¿Ya estas registrado? <a href="{% url 'IniciarSesion' %}">Inicia sesión</a></p>
                    </form>
                </div>
            </div>
        </div>
</body>


</html>

gestionAccidentes/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="/static/css/styleView.css" rel="stylesheet">



</head>

<body>
    {% block content %} {% endblock %}
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
</body>

</html>

gestionAccidentes/templates/detalles.html
{% load crispy_forms_tags %}
<html>

<head>
    <link rel="stylesheet" href="/static/css/registrarAccidente.css">
    <link rel="stylesheet" href="/static/css/styleView.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'inicio' %}">
                <img src="/media/logo/icons8-accident-85.png" alt="" width="40" height="34" class="d-inline-block align-text-top"> Gestor de accidentes
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'inicio' %}">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'registrarAccidente' %}">Registrar Accidente</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'listaDeAccidentes' %}">Ver Accidentes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cerrarSesion' %}">Cerrar Sesión</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="d-flex justify-content-center align-items-center p-4">

        <div class="content col-10 py-0  px-0 box shadow bg-white">
            <h1 class="text-center p-2" style="background-color: blue;color:white">Resumen de accidente</h1>
            <div id="mapa" class="capas col-6 mx-5 mt-5"></div>
            <div id="datos" class="py-5 d-inline-block col-4 mx-2 ">

                <fieldset disabled style="border: none">


                    <form action="" method="POST" class="form-control" enctype="multipart/form-data" id="form">
                        {% csrf_token %}
                        <table class="mb-2">
                            <table>
                            {{form|crispy}}
                            <tr><label>Municipio*</label></tr>  
                            <tr><td><input value="{{accidente.municipio}}"></td></tr>
                        </table>
                            
                            <tr>
                                {{form2.cantVictimas|as_crispy_field}}
                            </tr>
                            {% if detalles.foto %}
                            <tr>
                                <div class="row mt-2">
                                    <h2 class="text-center">{{form2.foto.label}}:</h2>
                                </div>

                            </tr>
                            <div class="d-flex justify-content-center col-12"><img class="mw-100 " src="{{detalles.foto.url}}" class="mt-2"></div>
                            {% endif %}

                        </table>

                    </form>
                </fieldset>
                <a href="{% url 'listaDeAccidentes' %}"><button class=" d-grid col-10 mx-auto btn btn-primary">Regresar</button></a>

            </div>
        </div>
    </div>

    <div id="data"></div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="/static/js/mapaDetalles.js "></script>
    <script type="text/javascript" src="https://maps.google.com/maps/api/js?key=AIzaSyBsWMz4YiUjnc-WKTIWdMx7rmexq2I76E8"></script>
    <script src="/static/js/select.js">
    </script>
</body>

</html>

gestionAccidentes/templates/inicio.html
{% extends "base.html" %}

<html>
{% block content %}

<head>
    <link href="/static/css/style.css" rel="stylesheet">

</head>

<body>
    <div class="d-flex align-items-center justify-content-center">
        <div class="row content d-flex justify-content-center align-items-center" style="height:100vh">

            <div class="col-md-8">
                <div class="box shadow bg-white p-4">
                    <h1 class="text-center">Bienvenido al sistema de reporte de accidentes</h1>
                    <a href="{% url 'registrarAccidente' %}" class="d-grid gap-2 col-10 mx-auto mt-5"><button type="button" class="btn btn-primary btn-lg ">Registrar accidente</button></a>
                    <a href="{% url 'listaDeAccidentes' %}" class="d-grid gap-2 col-10 mx-auto mt-3"><button type="button" class="btn btn-primary btn-lg">Ver accidentes</button></a>
                    <div class="d-flex justify-content-end mt-5">
                        {% if user.is_authenticated %}
                        <a href="{% url 'cerrarSesion' %}"><button type="button" class="btn btn-dark btn-lg">Cerrar Sesión</button></a> {% endif %}
                    </div>
                </div>


            </div>
        </div>

    </div>
    {% endblock %}
</body>

</html>

gestionAccidentes/templates/listaDeAccidentes.html
{% extends "base.html"%} {% load crispy_forms_tags %}
<html>
</head>

<body>

    <head>
        <title>Lista de accidentes</title>
    </head>

    <body>

        {% block content %}
        <nav class="navbar navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'inicio' %}">
                    <img src="/media/logo/icons8-accident-85.png" alt="" width="40" height="34" class="d-inline-block align-text-top"> Gestor de accidentes
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'inicio' %}">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'registrarAccidente' %}">Registrar Accidente</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'listaDeAccidentes' %}">Ver Accidentes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'cerrarSesion' %}">Cerrar Sesión</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="mt-2 px-2 form-floaing col">
            <form method="POST">
                {% csrf_token %}
                <div class="form-row">
                    <div class="input-group">
                        {{filtro.filtrar_por|as_crispy_field}}
                        <div class="mx-5">{{filtro.buscar|as_crispy_field}}</div>
                    </div>
                </div>
                <div class="row mt-3 ">
                    <div class="col text-center"><input type="submit" class="col-9 btn btn-success mb-3" value="Filtrar"></div>
                </div>

            </form>
            <div class="col text-center"><a href="{% url 'listaDeAccidentes' %} "><button class="btn col-9 btn-secondary">Mostrar todos</button></a></div>
        </div>
        <p class="col text-center mt-2">
            <strong>Advertencia:</strong> Si detecta algun accidente fraudulento, por favor reportelo (solo se le contara un reporte por accidente)
        </p>
        <div class="shadow box shadow" style="height:100vh">
            <table class="table text-center table-striped table-bordered">
                <thead class="thead-dark">
                    <tr>
                        
                        <th scope="col">Departamento</th>
                        <th scope="col">Municipio</th>
                        <th scope="col">Lugar</th>
                        <th scope="col">Fecha</th>
                        <th scope="col">Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for accidente in accidentes %}
                    <tr>
                        
                        <td>{{accidente.departamento}}</td>
                        <td>{{accidente.municipio}}</td>
                        <td>{{accidente.lugar}}</td>
                        <td>{{accidente.fecha}} </td>
                        <td style="width: 15%">
                            <a href="{% url 'detalles' accidente.id %}"><button class="btn btn-success">Detalles</button></a>
                            <a href="{% url 'reportar' accidente.id %}"><button class="btn mx-2 btn-danger" >Reportar</button></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        </div>
        {% endblock %}
    </body>
    <script src="/static/js/municipios.js"></script>

</html>

gestionAccidentes/templates/registrarAccidente.html
{% load crispy_forms_tags %}
<html>

<head>
    <link rel="stylesheet" href="/static/css/registrarAccidente.css">
    <link rel="stylesheet" href="/static/css/styleView.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>

<body>
    <nav class="navbar navbar-dark bg-white">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'inicio' %}">
                <img src="/media/logo/icons8-accident-85.png" alt="" width="40" height="34" class="d-inline-block align-text-top"> Gestor de accidentes
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'inicio' %}">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'registrarAccidente' %}">Registrar accidente</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'listaDeAccidentes' %}">Ver accidentes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'IniciarSesion' %}">Cerrar Sesión</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="p-4">
        <div class="content col-12 p-2 px-0 box shadow bg-white">
            <div id="mapa" class="capas col-6 mx-2 mt-5"></div>
            <div id="datos" class="d-inline-block col-4 mx-3 ">
                <input type="text" class="col-8" id="place_input">
                <p>Ej: Cojutepeque Cuscatlan</p>
                <div id="form">
                    
                    <form action="" method="POST" class="form-control" enctype="multipart/form-data" id="form">
                        <table>
                        {% csrf_token %} {{form|crispy}}
                        <tr><label>Municipio*</label></tr>                                                       
                    <tr><th><select required name="municipio" id="id_municipio"></select></th></tr>
                </table>                                                       
                        <tr><td><strong>Opcional:</strong></td></tr>
                        <table>{{form2|crispy}}</table>
                                         
                    
                        <input type="submit" class="btn btn-primary col-12 mt-2" value="Guardar">
                    </form>
                
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="/static/js/mapa.js "></script>
    <script type="text/javascript" src="https://maps.google.com/maps/api/js?key=AIzaSyBsWMz4YiUjnc-WKTIWdMx7rmexq2I76E8&libraries=places"></script>
    <script src="/static/js/municipios.js">
    </script>



</body>

</html>